columns_map:
  timestamp: "Marca temporal"
  origen: "¿Cuál es su procedencia?"
  ciudad_es: "En el caso de España, ¿qué ciudad?"
  pais_intl: "En el caso de Internacional, ¿qué país?"
  n_adultos: "# ¿Con cuántas personas viajas? (adultos)"
  n_menores: "# ¿Con cuántos menores viajas?"
  fin_semana: "Con el fin de semana"
 
schema:
  required: [timestamp, origen, n_adultos, n_menores, fin_semana]
 
types:
  timestamp: datetime
  origen: category
  ciudad_es: string
  pais_intl: string
  n_adultos: int
  n_menores: int
  fin_semana: category
 
domains:
  origen:
    allowed: ["Alcoi", "España", "Internacional", "Comunidad Valenciana"]
  fin_semana:
    allowed: ["Sí", "No", "No entiendo la pregunta"]
 
ranges:
  n_adultos: {min: 0, max: 10}
  n_menores: {min: 0, max: 10}
 
uniques:
  - [timestamp, origen]
 
conditionals:
  - if: {origen: "España"}
    then: {require_not_null: ["ciudad_es"]}
  - if: {origen: "Internacional"}
    then: {require_not_null: ["pais_intl"]}
  - rule: "n_adultos + n_menores >= 1"
 
severity:
  missing_column: error
  type_mismatch: error
  domain_violation: warning
  range_violation: warning
  uniqueness_violation: error
  conditional_violation: error